### ISSUE TITLE
Visibility of Awesome List

### ISSUE THREAD

**Issue by bitsgalore** [digipres/digipres.github.io#44]
At the moment it's quite hard to find the Awesome List from the digipres home page (<http://www.digipres.org/>): the only link to it is hidden away in the "Community Resources" menu.

Perhaps this could be made more prominent with a dedicated box/icon, just like "Find Preservation Tools",  "Find File Formats", etc?

**Comment by anjackson** [comment]
I've tried to make it a big more prominent, but it perhaps needs a more thorough review.

**Comment by bitsgalore** [comment]
@anjackson Thanks Andy, much better. I'll close the issue now.
